In [ ]:
import numpy as np

#1d array
arr1 = np.array([1,2,3,4,5,6])
#2d array
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])
#3d array
arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

#array dimentions
print(arr1.ndim,arr2.ndim,arr3.ndim)
#shape
print(arr1.shape,arr2.shape,arr3.shape)
#type 
print(arr1.dtype,arr2.dtype,arr3.dtype)
#size
print(arr1.size,arr2.size,arr3.size)



### Random Numpy Veues generators

In [19]:
arr = np.random.rand(3,3)

# normal from 
print(arr)
#type 
print(type(arr))
# numpy type 
print(arr.dtype)
#array dimensions
print(arr.ndim)
#shape
print(arr.shape)
#size
print(arr.size)

[[0.08136118 0.35818984 0.1876864 ]
 [0.22806555 0.58104123 0.54469127]
 [0.15852324 0.54942854 0.62479892]]
<class 'numpy.ndarray'>
float64
2
(3, 3)
9


### Random generator int veluse

In [28]:
arr = np.random.randint(1,100,(3,3))

# normal from 
print(arr)
#type 
print(type(arr))
# numpy type 
print(arr.dtype)
#array dimensions
print(arr.ndim)
#shape
print(arr.shape)
#size
print(arr.size)

[[65 74 41]
 [ 2 51 32]
 [62  1 25]]
<class 'numpy.ndarray'>
int64
2
(3, 3)
9


### Randon float values generators

In [29]:
arr = np.random.uniform(1,100,(3,3))

# normal from 
print(arr)
#type 
print(type(arr))
# numpy type 
print(arr.dtype)
#array dimensions
print(arr.ndim)
#shape
print(arr.shape)
#size
print(arr.size)

[[52.23629518 75.94170402 29.94209432]
 [96.40888882 90.87165071 70.30914025]
 [65.97034224 34.30455254 76.5308095 ]]
<class 'numpy.ndarray'>
float64
2
(3, 3)
9


### Array generator with np arange funtions

In [35]:
arr = np.arange(1,15,1)
# normal from 
print(arr)
#type 
print(type(arr))
# numpy type 
print(arr.dtype)
#shape
print(arr.shape)
#array dimensions
print(arr.ndim)
#size
print(arr.size)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
int64
(14,)
1
14


### generator metrix with arange 

In [39]:
arr = np.arange(1,10,1).reshape(3,3)
# normal from 
print(arr)
#type 
print(type(arr))
# numpy type 
print(arr.dtype)
#shape
print(arr.shape)
#array dimensions
print(arr.ndim)
#size
print(arr.size)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


### Np linspace(start, end , koita)

In [43]:
arr = np.linspace(1,10,100)
# normal from 
print(arr)
#type 
print(type(arr))
# numpy type 
print(arr.dtype)
#shape
print(arr.shape)
#array dimensions
print(arr.ndim)
#size
print(arr.size)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [49]:
#np.logspace(start,end(included),koita
arr = np.logspace(1,4,5)
# normal from 
print(arr)
#type 
print(type(arr))
# numpy type 
print(arr.dtype)
#shape
print(arr.shape)
#array dimensions
print(arr.ndim)
#size
print(arr.size)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]
<class 'numpy.ndarray'>
float64
(5,)
1
5
